export const boardData = [
    {
      name: 'Gretchen Schleifer',
      country: 'United States',
      dons: 200,
      points: 200,
    },
    {
      name: 'John Doe',
      country: 'Canada',
      dons: 150,
      points: 150, 
    },
    {
      name: 'Alice Johnson',
      country: 'United Kingdom',
      dons: 180,
      points: 180, 
    },
    {
      name: 'Eva Smith',
      country: 'Australia',
      dons: 220,
      points: 220, 
    },
    {
      name: 'Michael Brown',
      country: 'Germany',
      dons: 170,
      points: 170, 
    },
    {
      name: 'Sophia Wilson',
      country: 'France',
      dons: 190,
      points: 190, 
    },
    {
      name: 'William Lee',
      country: 'Japan',
      dons: 210,
      points: 210, 
    },
    {
      name: 'Olivia Taylor',
      country: 'Italy',
      dons: 160,
      points: 160, 
    },
    {
      name: 'Daniel Anderson',
      country: 'Spain',
      dons: 230,
      points: 230, 
    },
    {
      name: 'Emma Martinez',
      country: 'Brazil',
      dons: 140,
      points: 140, 
    },
    {
      name: 'Alexander Perez',
      country: 'United States',
      dons: 200,
      points: 200,
    },
    {
      name: 'Mia Gonzalez',
      country: 'China',
      dons: 180,
      points: 180, 
    },
    {
      name: 'Liam Rodriguez',
      country: 'India',
      dons: 210,
      points: 210, 
    },
    {
      name: 'Ava Hernandez',
      country: 'Mexico',
      dons: 150,
      points: 150, 
    },
    {
      name: 'James Smith',
      country: 'South Korea',
      dons: 190,
      points: 190, 
    },
    {
      name: 'Charlotte Lee',
      country: 'Argentina',
      dons: 220,
      points: 220, 
    },
    {
      name: 'Benjamin Kim',
      country: 'South Africa',
      dons: 160,
      points: 160, 
    },
    {
      name: 'Abigail Nguyen',
      country: 'Nigeria',
      dons: 200,
      points: 200, 
    },
    {
      name: 'Lucas Brown',
      country: 'Egypt',
      dons: 170,
      points: 170, 
    },
    {
      name: 'Sophia Smith',
      country: 'Turkey',
      dons: 180,
      points: 180, 
    },
  ];
  