export const chatData = [
    {
        name: 'James Dias',
        time: '12:45',
        text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        avatar: '',
        status: 'Delivered',
        isResponse: false,
    },
    {
        name: 'Ryan Culhane',
        time: '12:46',
        text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        avatar: '',
        status: 'Delivered',
        isResponse: false,
    },
    {
        name: 'Roger Bergson',
        time: '12:47',
        text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        avatar: '',
        status: 'Delivered',
        isResponse: false,
    },
    {
        name: 'Mira Schleifer',
        time: '12:50',
        text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        avatar: '',
        status: 'Delivered',
        isResponse: false,
    },
    {
        name: 'Kaiya Gouse',
        time: '13:05',
        text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        avatar: '',
        status: 'Delivered',
        isResponse: false,
    },
    {
        name: 'admin',
        time: '13:06',
        text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        avatar: '',
        status: 'Delivered',
        isResponse: true,
    },
    {
        name: 'Ryan Culhane',
        time: '12:46',
        text: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        avatar: '',
        status: 'Delivered',
        isResponse: false,
    },
]